{{- if .Values.monitoring.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "video-ai.fullname" . }}
  labels:
    {{- include "video-ai.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "video-ai.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  endpoints:
    - port: metrics
      interval: {{ .Values.monitoring.prometheus.serviceMonitor.interval }}
      path: /metrics
{{- end }}
